/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock_maintanance;

/**
 *
 * @author karuna
 */

import Beans.Creating_Account;
import Beans.Login_bean;
import DAO.Create_Account;
import javax.swing.*;
import javax.swing.JOptionPane;
import java.awt.*;


public class Create_User extends javax.swing.JFrame {

    /**
     * Creates new form Create_User
     */
    
    //Creating Objects for the imported files
    Creating_Account Bean=new Creating_Account();
    Login_bean Bean_L=new Login_bean();
    Create_Account Dao=new Create_Account();
    
    public Create_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Group_button = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Create_Account = new javax.swing.JLabel();
        L_Fname = new javax.swing.JLabel();
        txt_Firstname = new javax.swing.JTextField();
        L_lastname = new javax.swing.JLabel();
        txt_Lastname = new javax.swing.JTextField();
        L_age = new javax.swing.JLabel();
        L_gender = new javax.swing.JLabel();
        R_Male = new javax.swing.JRadioButton();
        R_Female = new javax.swing.JRadioButton();
        R_Other = new javax.swing.JRadioButton();
        L_phone = new javax.swing.JLabel();
        txt_Phone = new javax.swing.JTextField();
        L_email_id = new javax.swing.JLabel();
        L_Address = new javax.swing.JLabel();
        B_create_account = new javax.swing.JButton();
        B_Reset = new javax.swing.JButton();
        B_Cancel = new javax.swing.JButton();
        L_DOB = new javax.swing.JLabel();
        txt_Dob = new javax.swing.JFormattedTextField();
        L_Addhar = new javax.swing.JLabel();
        L_Qualifiction = new javax.swing.JLabel();
        txt_qualification = new javax.swing.JTextField();
        L_Experience = new javax.swing.JLabel();
        L_Username = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        L_Password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        c_Experience = new javax.swing.JComboBox();
        txt_Aadhar_no = new javax.swing.JFormattedTextField();
        txt_Age = new javax.swing.JSpinner();
        txt_Email_id = new javax.swing.JTextField();
        L_Position = new javax.swing.JLabel();
        C_Position = new javax.swing.JComboBox();
        txt_Address = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Create_Account.setBackground(new java.awt.Color(255, 255, 255));
        Create_Account.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Create_Account.setText("Create User Account");

        L_Fname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_Fname.setText("First Name :");

        txt_Firstname.setToolTipText("First Name");
        txt_Firstname.setNextFocusableComponent(txt_Lastname);
        txt_Firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_FirstnameKeyPressed(evt);
            }
        });

        L_lastname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_lastname.setText("Last Name :");

        txt_Lastname.setToolTipText("Last Name");
        txt_Lastname.setNextFocusableComponent(txt_Age);

        L_age.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_age.setText("Age :");

        L_gender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_gender.setText("Gender :");

        Group_button.add(R_Male);
        R_Male.setText("Male");
        R_Male.setToolTipText("Male");
        R_Male.setNextFocusableComponent(txt_Phone);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, R_Male, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), R_Male, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        Group_button.add(R_Female);
        R_Female.setText("Female");
        R_Female.setToolTipText("Female");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, R_Female, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), R_Female, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        Group_button.add(R_Other);
        R_Other.setText("Other");
        R_Other.setToolTipText("Others");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, R_Other, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), R_Other, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        L_phone.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_phone.setText("Phone :");

        txt_Phone.setColumns(10);
        txt_Phone.setToolTipText("Phone Number");

        L_email_id.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_email_id.setText("Email_Id :");

        L_Address.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_Address.setText("Address :");

        B_create_account.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        B_create_account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Create.png"))); // NOI18N
        B_create_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_create_accountActionPerformed(evt);
            }
        });

        B_Reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        B_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ResetActionPerformed(evt);
            }
        });

        B_Cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        B_Cancel.setText("Cancel");
        B_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CancelActionPerformed(evt);
            }
        });

        L_DOB.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_DOB.setText("D.O.B :");

        try {
            txt_Dob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_Dob.setToolTipText("yyyy-mm-dd");
        txt_Dob.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Dob.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_Dob.setNextFocusableComponent(txt_Aadhar_no);

        L_Addhar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_Addhar.setText("Aadhar No :");

        L_Qualifiction.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_Qualifiction.setText("Qualification :");

        txt_qualification.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_qualification.setToolTipText("Qualification");
        txt_qualification.setNextFocusableComponent(c_Experience);

        L_Experience.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_Experience.setText("Experience :");

        L_Username.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_Username.setText("Username :");

        txt_Username.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_Username.setToolTipText("Username");
        txt_Username.setNextFocusableComponent(txt_password);

        L_Password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_Password.setText("Password :");

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_password.setToolTipText("Password");

        c_Experience.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        c_Experience.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 - 2 Years", "2 - 4 Years", "5 - 6 Years", "More than 6" }));
        c_Experience.setNextFocusableComponent(txt_Username);

        try {
            txt_Aadhar_no.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_Aadhar_no.setToolTipText("xxxx-xxxx-xxxx");
        txt_Aadhar_no.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_Aadhar_no.setNextFocusableComponent(txt_qualification);

        txt_Age.setToolTipText("Age");
        txt_Age.setNextFocusableComponent(R_Male);

        txt_Email_id.setToolTipText("Email Id");
        txt_Email_id.setNextFocusableComponent(txt_Aadhar_no);

        L_Position.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        L_Position.setText("Position :");

        C_Position.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        C_Position.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Employee" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_Address)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(L_lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(L_Fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(L_age, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(L_phone, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(L_email_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(L_gender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Firstname)
                            .addComponent(txt_Lastname)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(R_Male)
                                .addGap(18, 18, 18)
                                .addComponent(R_Female)
                                .addGap(18, 18, 18)
                                .addComponent(R_Other))
                            .addComponent(txt_Phone)
                            .addComponent(txt_Email_id)
                            .addComponent(txt_Address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_Experience, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_Password, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_Addhar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_Position, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_DOB, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_Qualifiction)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_Experience, 0, 221, Short.MAX_VALUE)
                    .addComponent(txt_password)
                    .addComponent(txt_qualification)
                    .addComponent(txt_Aadhar_no)
                    .addComponent(txt_Dob)
                    .addComponent(C_Position, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(148, 148, 148)
                .addComponent(L_Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(484, 484, 484))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(B_create_account)
                        .addGap(125, 125, 125)
                        .addComponent(B_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(B_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(639, 639, 639)
                        .addComponent(Create_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Create_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(L_Fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(L_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Dob, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Aadhar_no, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Addhar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Qualifiction, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_Male)
                    .addComponent(R_Female)
                    .addComponent(R_Other)
                    .addComponent(L_Experience, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Experience, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_phone)
                    .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_email_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txt_Email_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(B_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_create_account, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        txt_Dob.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1868, 1047));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ResetActionPerformed
        // this is used to Reset the values to empty by using SetText,setValue and setSelectedItem
        
        
        txt_Firstname.setText("");
        txt_Lastname.setText("");
        txt_Age.setValue(0);
        txt_Phone.setText("");
        txt_Email_id.setText("");
        txt_Address.setText("");
        txt_Dob.setText("");
        txt_Aadhar_no.setText("");
        txt_qualification.setText("");
        c_Experience.setSelectedItem("0 - 2 Years");
        txt_Username.setText("");
        txt_password.setText("");
    }//GEN-LAST:event_B_ResetActionPerformed

    private void B_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CancelActionPerformed
        // the Below code is used to close the frame by dispose() method
        dispose();
    }//GEN-LAST:event_B_CancelActionPerformed

    private void B_create_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_create_accountActionPerformed
        /*  we are using getText,getSelection,getSelectedItem to get the values from the frame and passing the value to the bean files
            and by using the if condition we are verifying the username and password */
        String Fname,Lname,Phone,Email,Gender,Address,Dob,Aadhar,Qualification,Experience,Username,Password,Position,Creater;
        Fname =txt_Firstname.getText();
        Lname=txt_Lastname.getText();
        int Age=(Integer)txt_Age.getValue();
        Phone=txt_Phone.getText();
        Email=txt_Email_id.getText();
        Gender=Group_button.getSelection().getActionCommand();
        Address=txt_Address.getText();
        Dob = txt_Dob.getText();
        Aadhar=txt_Aadhar_no.getText();
        Qualification =txt_qualification.getText();
        Experience=c_Experience.getSelectedItem().toString();
        Username=txt_Username.getText();
        Password=txt_password.getText();
        Position=C_Position.getSelectedItem().toString();
        Creater="Admin";
        
        String Values = "('" + Fname + "','" + Lname + "'," + Age + ",'" + Gender + "','" + Phone + "','" + Email + "','" + Address + "','" + Dob + "','" + Aadhar + "','" + Qualification + "','" + Experience + "'"+Position+"'"+Creater+"')";
        String UPvalue="('"+Username+"','"+Password+"');";
        
        Bean.setValues(Values);
        Bean.setUpvalue(UPvalue);
        
        int s=Dao.getValue();
        if(s == 1){
            JOptionPane.showMessageDialog(this,"Account created Successfully");
            dispose();
        }
        else if(s==0){
            JOptionPane.showMessageDialog(this,"Enter All Values");
        }
        else{
            JOptionPane.showMessageDialog(this,"Enter Values Correctly");
        
        }
        
    }//GEN-LAST:event_B_create_accountActionPerformed

    private void txt_FirstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FirstnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FirstnameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Cancel;
    private javax.swing.JButton B_Reset;
    private javax.swing.JButton B_create_account;
    private javax.swing.JComboBox C_Position;
    private javax.swing.JLabel Create_Account;
    private javax.swing.ButtonGroup Group_button;
    private javax.swing.JLabel L_Addhar;
    private javax.swing.JLabel L_Address;
    private javax.swing.JLabel L_DOB;
    private javax.swing.JLabel L_Experience;
    private javax.swing.JLabel L_Fname;
    private javax.swing.JLabel L_Password;
    private javax.swing.JLabel L_Position;
    private javax.swing.JLabel L_Qualifiction;
    private javax.swing.JLabel L_Username;
    private javax.swing.JLabel L_age;
    private javax.swing.JLabel L_email_id;
    private javax.swing.JLabel L_gender;
    private javax.swing.JLabel L_lastname;
    private javax.swing.JLabel L_phone;
    private javax.swing.JRadioButton R_Female;
    private javax.swing.JRadioButton R_Male;
    private javax.swing.JRadioButton R_Other;
    private javax.swing.JComboBox c_Experience;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JFormattedTextField txt_Aadhar_no;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JSpinner txt_Age;
    private javax.swing.JFormattedTextField txt_Dob;
    private javax.swing.JTextField txt_Email_id;
    private javax.swing.JTextField txt_Firstname;
    private javax.swing.JTextField txt_Lastname;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_Username;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_qualification;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
